// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: logisticPack/logistic_pack_api/v1/logistic_pack_api.proto

package logistic_pack_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Foo     uint64                 `protobuf:"varint,2,opt,name=foo,proto3" json:"foo,omitempty"`
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Pack) Reset() {
	*x = Pack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{0}
}

func (x *Pack) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pack) GetFoo() uint64 {
	if x != nil {
		return x.Foo
	}
	return 0
}

func (x *Pack) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type DescribePackV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackId uint64 `protobuf:"varint,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
}

func (x *DescribePackV1Request) Reset() {
	*x = DescribePackV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribePackV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePackV1Request) ProtoMessage() {}

func (x *DescribePackV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePackV1Request.ProtoReflect.Descriptor instead.
func (*DescribePackV1Request) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{1}
}

func (x *DescribePackV1Request) GetPackId() uint64 {
	if x != nil {
		return x.PackId
	}
	return 0
}

type DescribePackV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Pack `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DescribePackV1Response) Reset() {
	*x = DescribePackV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribePackV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePackV1Response) ProtoMessage() {}

func (x *DescribePackV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePackV1Response.ProtoReflect.Descriptor instead.
func (*DescribePackV1Response) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{2}
}

func (x *DescribePackV1Response) GetValue() *Pack {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreatePackV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *CreatePackV1Request) Reset() {
	*x = CreatePackV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackV1Request) ProtoMessage() {}

func (x *CreatePackV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackV1Request.ProtoReflect.Descriptor instead.
func (*CreatePackV1Request) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePackV1Request) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

type CreatePackV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackId uint64 `protobuf:"varint,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
}

func (x *CreatePackV1Response) Reset() {
	*x = CreatePackV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackV1Response) ProtoMessage() {}

func (x *CreatePackV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackV1Response.ProtoReflect.Descriptor instead.
func (*CreatePackV1Response) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePackV1Response) GetPackId() uint64 {
	if x != nil {
		return x.PackId
	}
	return 0
}

type ListPackV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPackV1Request) Reset() {
	*x = ListPackV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPackV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackV1Request) ProtoMessage() {}

func (x *ListPackV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackV1Request.ProtoReflect.Descriptor instead.
func (*ListPackV1Request) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{5}
}

type ListPackV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Pack `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListPackV1Response) Reset() {
	*x = ListPackV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPackV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackV1Response) ProtoMessage() {}

func (x *ListPackV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackV1Response.ProtoReflect.Descriptor instead.
func (*ListPackV1Response) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListPackV1Response) GetItems() []*Pack {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemovePackV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackId uint64 `protobuf:"varint,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
}

func (x *RemovePackV1Request) Reset() {
	*x = RemovePackV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePackV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackV1Request) ProtoMessage() {}

func (x *RemovePackV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackV1Request.ProtoReflect.Descriptor instead.
func (*RemovePackV1Request) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemovePackV1Request) GetPackId() uint64 {
	if x != nil {
		return x.PackId
	}
	return 0
}

type RemovePackV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemovePackV1Response) Reset() {
	*x = RemovePackV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePackV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackV1Response) ProtoMessage() {}

func (x *RemovePackV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackV1Response.ProtoReflect.Descriptor instead.
func (*RemovePackV1Response) Descriptor() ([]byte, []int) {
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePackV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto protoreflect.FileDescriptor

var file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDesc = []byte{
	0x0a, 0x39, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x2f, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x63,
	0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x73, 0x74, 0x6f,
	0x72, 0x6d, 0x62, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x04, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x6f, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x12,
	0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x39, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x22, 0x56, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x6d, 0x62, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6f,
	0x6f, 0x22, 0x2f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x6d, 0x62, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0xbb, 0x01, 0x0a, 0x16, 0x4c, 0x6f,
	0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0xa0, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x12, 0x37, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x62,
	0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70,
	0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x38, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x62, 0x65, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x15, 0x12, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x2f, 0x7b, 0x70,
	0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x62, 0x65, 0x61, 0x76, 0x65,
	0x72, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x2d, 0x70, 0x61, 0x63, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescOnce sync.Once
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescData = file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDesc
)

func file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescGZIP() []byte {
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescOnce.Do(func() {
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescData)
	})
	return file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDescData
}

var file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_goTypes = []interface{}{
	(*Pack)(nil),                   // 0: stormbeaver.logistic_pack_api.v1.Pack
	(*DescribePackV1Request)(nil),  // 1: stormbeaver.logistic_pack_api.v1.DescribePackV1Request
	(*DescribePackV1Response)(nil), // 2: stormbeaver.logistic_pack_api.v1.DescribePackV1Response
	(*CreatePackV1Request)(nil),    // 3: stormbeaver.logistic_pack_api.v1.CreatePackV1Request
	(*CreatePackV1Response)(nil),   // 4: stormbeaver.logistic_pack_api.v1.CreatePackV1Response
	(*ListPackV1Request)(nil),      // 5: stormbeaver.logistic_pack_api.v1.ListPackV1Request
	(*ListPackV1Response)(nil),     // 6: stormbeaver.logistic_pack_api.v1.ListPackV1Response
	(*RemovePackV1Request)(nil),    // 7: stormbeaver.logistic_pack_api.v1.RemovePackV1Request
	(*RemovePackV1Response)(nil),   // 8: stormbeaver.logistic_pack_api.v1.RemovePackV1Response
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_depIdxs = []int32{
	9, // 0: stormbeaver.logistic_pack_api.v1.Pack.created:type_name -> google.protobuf.Timestamp
	0, // 1: stormbeaver.logistic_pack_api.v1.DescribePackV1Response.value:type_name -> stormbeaver.logistic_pack_api.v1.Pack
	0, // 2: stormbeaver.logistic_pack_api.v1.ListPackV1Response.items:type_name -> stormbeaver.logistic_pack_api.v1.Pack
	1, // 3: stormbeaver.logistic_pack_api.v1.LogisticPackApiService.DescribePackV1:input_type -> stormbeaver.logistic_pack_api.v1.DescribePackV1Request
	2, // 4: stormbeaver.logistic_pack_api.v1.LogisticPackApiService.DescribePackV1:output_type -> stormbeaver.logistic_pack_api.v1.DescribePackV1Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_init() }
func file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_init() {
	if File_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribePackV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribePackV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPackV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPackV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePackV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePackV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_goTypes,
		DependencyIndexes: file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_depIdxs,
		MessageInfos:      file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_msgTypes,
	}.Build()
	File_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto = out.File
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_rawDesc = nil
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_goTypes = nil
	file_logisticPack_logistic_pack_api_v1_logistic_pack_api_proto_depIdxs = nil
}
