// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: logisticPack/logistic_pack_api/v1/logistic_pack_api.proto

package logistic_pack_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Pack with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Pack) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PackValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// PackValidationError is the validation error returned by Pack.Validate if the
// designated constraints aren't met.
type PackValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackValidationError) ErrorName() string { return "PackValidationError" }

// Error satisfies the builtin error interface
func (e PackValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPack.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackValidationError{}

// Validate checks the field values on DescribePackV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackId() <= 0 {
		return DescribePackV1RequestValidationError{
			field:  "PackId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribePackV1RequestValidationError is the validation error returned by
// DescribePackV1Request.Validate if the designated constraints aren't met.
type DescribePackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePackV1RequestValidationError) ErrorName() string {
	return "DescribePackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePackV1RequestValidationError{}

// Validate checks the field values on DescribePackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribePackV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribePackV1ResponseValidationError is the validation error returned by
// DescribePackV1Response.Validate if the designated constraints aren't met.
type DescribePackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePackV1ResponseValidationError) ErrorName() string {
	return "DescribePackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePackV1ResponseValidationError{}

// Validate checks the field values on CreatePackV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 3 {
		return CreatePackV1RequestValidationError{
			field:  "Name",
			reason: "value length must be at least 3 runes",
		}
	}

	if len(m.GetName()) > 256 {
		return CreatePackV1RequestValidationError{
			field:  "Name",
			reason: "value length must be at most 256 bytes",
		}
	}

	return nil
}

// CreatePackV1RequestValidationError is the validation error returned by
// CreatePackV1Request.Validate if the designated constraints aren't met.
type CreatePackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePackV1RequestValidationError) ErrorName() string {
	return "CreatePackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePackV1RequestValidationError{}

// Validate checks the field values on CreatePackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PackId

	return nil
}

// CreatePackV1ResponseValidationError is the validation error returned by
// CreatePackV1Response.Validate if the designated constraints aren't met.
type CreatePackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePackV1ResponseValidationError) ErrorName() string {
	return "CreatePackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePackV1ResponseValidationError{}

// Validate checks the field values on ListPackV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListPackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ListPackV1RequestValidationError is the validation error returned by
// ListPackV1Request.Validate if the designated constraints aren't met.
type ListPackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackV1RequestValidationError) ErrorName() string {
	return "ListPackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackV1RequestValidationError{}

// Validate checks the field values on ListPackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPackV1ResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListPackV1ResponseValidationError is the validation error returned by
// ListPackV1Response.Validate if the designated constraints aren't met.
type ListPackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackV1ResponseValidationError) ErrorName() string {
	return "ListPackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackV1ResponseValidationError{}

// Validate checks the field values on RemovePackV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackId() <= 0 {
		return RemovePackV1RequestValidationError{
			field:  "PackId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemovePackV1RequestValidationError is the validation error returned by
// RemovePackV1Request.Validate if the designated constraints aren't met.
type RemovePackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePackV1RequestValidationError) ErrorName() string {
	return "RemovePackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePackV1RequestValidationError{}

// Validate checks the field values on RemovePackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemovePackV1ResponseValidationError is the validation error returned by
// RemovePackV1Response.Validate if the designated constraints aren't met.
type RemovePackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePackV1ResponseValidationError) ErrorName() string {
	return "RemovePackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePackV1ResponseValidationError{}
