// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package logistic_pack_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogisticPackApiServiceClient is the client API for LogisticPackApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogisticPackApiServiceClient interface {
	// DescribePackV1 - Describe a pack
	DescribePackV1(ctx context.Context, in *DescribePackV1Request, opts ...grpc.CallOption) (*DescribePackV1Response, error)
}

type logisticPackApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogisticPackApiServiceClient(cc grpc.ClientConnInterface) LogisticPackApiServiceClient {
	return &logisticPackApiServiceClient{cc}
}

func (c *logisticPackApiServiceClient) DescribePackV1(ctx context.Context, in *DescribePackV1Request, opts ...grpc.CallOption) (*DescribePackV1Response, error) {
	out := new(DescribePackV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.logistic_pack_api.v1.LogisticPackApiService/DescribePackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticPackApiServiceServer is the server API for LogisticPackApiService service.
// All implementations must embed UnimplementedLogisticPackApiServiceServer
// for forward compatibility
type LogisticPackApiServiceServer interface {
	// DescribePackV1 - Describe a pack
	DescribePackV1(context.Context, *DescribePackV1Request) (*DescribePackV1Response, error)
	mustEmbedUnimplementedLogisticPackApiServiceServer()
}

// UnimplementedLogisticPackApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogisticPackApiServiceServer struct {
}

func (UnimplementedLogisticPackApiServiceServer) DescribePackV1(context.Context, *DescribePackV1Request) (*DescribePackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribePackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) mustEmbedUnimplementedLogisticPackApiServiceServer() {
}

// UnsafeLogisticPackApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogisticPackApiServiceServer will
// result in compilation errors.
type UnsafeLogisticPackApiServiceServer interface {
	mustEmbedUnimplementedLogisticPackApiServiceServer()
}

func RegisterLogisticPackApiServiceServer(s grpc.ServiceRegistrar, srv LogisticPackApiServiceServer) {
	s.RegisterService(&LogisticPackApiService_ServiceDesc, srv)
}

func _LogisticPackApiService_DescribePackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).DescribePackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.logistic_pack_api.v1.LogisticPackApiService/DescribePackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).DescribePackV1(ctx, req.(*DescribePackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// LogisticPackApiService_ServiceDesc is the grpc.ServiceDesc for LogisticPackApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogisticPackApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.logistic_pack_api.v1.LogisticPackApiService",
	HandlerType: (*LogisticPackApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribePackV1",
			Handler:    _LogisticPackApiService_DescribePackV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logisticPack/logistic_pack_api/v1/logistic_pack_api.proto",
}
