// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package logistic_pack_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogisticPackApiServiceClient is the client API for LogisticPackApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogisticPackApiServiceClient interface {
	//CreatePackv1 - Create a new pack
	AddPackV1(ctx context.Context, in *AddPackV1Request, opts ...grpc.CallOption) (*AddPackV1Response, error)
	// GetPackV1 - Describe a pack
	GetPackV1(ctx context.Context, in *GetPackV1Request, opts ...grpc.CallOption) (*GetPackV1Response, error)
	//ListPackv1 - list all packs
	ListPackV1(ctx context.Context, in *ListPackV1Request, opts ...grpc.CallOption) (*ListPackV1Response, error)
	//UpdatePackV1 - update already existing pack
	UpdatePackV1(ctx context.Context, in *UpdatePackV1Request, opts ...grpc.CallOption) (*UpdatePackV1Response, error)
	//RemovePackV1 - remove a pack
	RemovePackV1(ctx context.Context, in *RemovePackV1Request, opts ...grpc.CallOption) (*RemovePackV1Response, error)
}

type logisticPackApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogisticPackApiServiceClient(cc grpc.ClientConnInterface) LogisticPackApiServiceClient {
	return &logisticPackApiServiceClient{cc}
}

func (c *logisticPackApiServiceClient) AddPackV1(ctx context.Context, in *AddPackV1Request, opts ...grpc.CallOption) (*AddPackV1Response, error) {
	out := new(AddPackV1Response)
	err := c.cc.Invoke(ctx, "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/AddPackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticPackApiServiceClient) GetPackV1(ctx context.Context, in *GetPackV1Request, opts ...grpc.CallOption) (*GetPackV1Response, error) {
	out := new(GetPackV1Response)
	err := c.cc.Invoke(ctx, "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/GetPackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticPackApiServiceClient) ListPackV1(ctx context.Context, in *ListPackV1Request, opts ...grpc.CallOption) (*ListPackV1Response, error) {
	out := new(ListPackV1Response)
	err := c.cc.Invoke(ctx, "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/ListPackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticPackApiServiceClient) UpdatePackV1(ctx context.Context, in *UpdatePackV1Request, opts ...grpc.CallOption) (*UpdatePackV1Response, error) {
	out := new(UpdatePackV1Response)
	err := c.cc.Invoke(ctx, "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/UpdatePackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticPackApiServiceClient) RemovePackV1(ctx context.Context, in *RemovePackV1Request, opts ...grpc.CallOption) (*RemovePackV1Response, error) {
	out := new(RemovePackV1Response)
	err := c.cc.Invoke(ctx, "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/RemovePackV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticPackApiServiceServer is the server API for LogisticPackApiService service.
// All implementations must embed UnimplementedLogisticPackApiServiceServer
// for forward compatibility
type LogisticPackApiServiceServer interface {
	//CreatePackv1 - Create a new pack
	AddPackV1(context.Context, *AddPackV1Request) (*AddPackV1Response, error)
	// GetPackV1 - Describe a pack
	GetPackV1(context.Context, *GetPackV1Request) (*GetPackV1Response, error)
	//ListPackv1 - list all packs
	ListPackV1(context.Context, *ListPackV1Request) (*ListPackV1Response, error)
	//UpdatePackV1 - update already existing pack
	UpdatePackV1(context.Context, *UpdatePackV1Request) (*UpdatePackV1Response, error)
	//RemovePackV1 - remove a pack
	RemovePackV1(context.Context, *RemovePackV1Request) (*RemovePackV1Response, error)
	mustEmbedUnimplementedLogisticPackApiServiceServer()
}

// UnimplementedLogisticPackApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogisticPackApiServiceServer struct {
}

func (UnimplementedLogisticPackApiServiceServer) AddPackV1(context.Context, *AddPackV1Request) (*AddPackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) GetPackV1(context.Context, *GetPackV1Request) (*GetPackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) ListPackV1(context.Context, *ListPackV1Request) (*ListPackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) UpdatePackV1(context.Context, *UpdatePackV1Request) (*UpdatePackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) RemovePackV1(context.Context, *RemovePackV1Request) (*RemovePackV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePackV1 not implemented")
}
func (UnimplementedLogisticPackApiServiceServer) mustEmbedUnimplementedLogisticPackApiServiceServer() {
}

// UnsafeLogisticPackApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogisticPackApiServiceServer will
// result in compilation errors.
type UnsafeLogisticPackApiServiceServer interface {
	mustEmbedUnimplementedLogisticPackApiServiceServer()
}

func RegisterLogisticPackApiServiceServer(s grpc.ServiceRegistrar, srv LogisticPackApiServiceServer) {
	s.RegisterService(&LogisticPackApiService_ServiceDesc, srv)
}

func _LogisticPackApiService_AddPackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).AddPackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/AddPackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).AddPackV1(ctx, req.(*AddPackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticPackApiService_GetPackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).GetPackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/GetPackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).GetPackV1(ctx, req.(*GetPackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticPackApiService_ListPackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).ListPackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/ListPackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).ListPackV1(ctx, req.(*ListPackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticPackApiService_UpdatePackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).UpdatePackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/UpdatePackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).UpdatePackV1(ctx, req.(*UpdatePackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticPackApiService_RemovePackV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePackV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticPackApiServiceServer).RemovePackV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StormBeaver.logistic_pack_api.v1.LogisticPackApiService/RemovePackV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticPackApiServiceServer).RemovePackV1(ctx, req.(*RemovePackV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// LogisticPackApiService_ServiceDesc is the grpc.ServiceDesc for LogisticPackApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogisticPackApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StormBeaver.logistic_pack_api.v1.LogisticPackApiService",
	HandlerType: (*LogisticPackApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPackV1",
			Handler:    _LogisticPackApiService_AddPackV1_Handler,
		},
		{
			MethodName: "GetPackV1",
			Handler:    _LogisticPackApiService_GetPackV1_Handler,
		},
		{
			MethodName: "ListPackV1",
			Handler:    _LogisticPackApiService_ListPackV1_Handler,
		},
		{
			MethodName: "UpdatePackV1",
			Handler:    _LogisticPackApiService_UpdatePackV1_Handler,
		},
		{
			MethodName: "RemovePackV1",
			Handler:    _LogisticPackApiService_RemovePackV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logisticPack/logistic_pack_api/v1/logistic_pack_api.proto",
}
