// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: logisticPack/logistic_pack_api/v1/logistic_pack_api.proto

package logistic_pack_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Pack with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Pack) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PackValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// PackValidationError is the validation error returned by Pack.Validate if the
// designated constraints aren't met.
type PackValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackValidationError) ErrorName() string { return "PackValidationError" }

// Error satisfies the builtin error interface
func (e PackValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPack.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackValidationError{}

// Validate checks the field values on AddPackV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AddPackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 3 {
		return AddPackV1RequestValidationError{
			field:  "Name",
			reason: "value length must be at least 3 runes",
		}
	}

	if len(m.GetName()) > 256 {
		return AddPackV1RequestValidationError{
			field:  "Name",
			reason: "value length must be at most 256 bytes",
		}
	}

	return nil
}

// AddPackV1RequestValidationError is the validation error returned by
// AddPackV1Request.Validate if the designated constraints aren't met.
type AddPackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddPackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddPackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddPackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddPackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddPackV1RequestValidationError) ErrorName() string { return "AddPackV1RequestValidationError" }

// Error satisfies the builtin error interface
func (e AddPackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddPackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddPackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddPackV1RequestValidationError{}

// Validate checks the field values on AddPackV1Response with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AddPackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PackId

	return nil
}

// AddPackV1ResponseValidationError is the validation error returned by
// AddPackV1Response.Validate if the designated constraints aren't met.
type AddPackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddPackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddPackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddPackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddPackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddPackV1ResponseValidationError) ErrorName() string {
	return "AddPackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddPackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddPackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddPackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddPackV1ResponseValidationError{}

// Validate checks the field values on GetPackV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetPackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackId() <= 0 {
		return GetPackV1RequestValidationError{
			field:  "PackId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// GetPackV1RequestValidationError is the validation error returned by
// GetPackV1Request.Validate if the designated constraints aren't met.
type GetPackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackV1RequestValidationError) ErrorName() string { return "GetPackV1RequestValidationError" }

// Error satisfies the builtin error interface
func (e GetPackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackV1RequestValidationError{}

// Validate checks the field values on GetPackV1Response with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetPackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPackV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetPackV1ResponseValidationError is the validation error returned by
// GetPackV1Response.Validate if the designated constraints aren't met.
type GetPackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackV1ResponseValidationError) ErrorName() string {
	return "GetPackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackV1ResponseValidationError{}

// Validate checks the field values on UpdatePackRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UpdatePackRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackId() <= 0 {
		return UpdatePackRequestValidationError{
			field:  "PackId",
			reason: "value must be greater than 0",
		}
	}

	if utf8.RuneCountInString(m.GetName()) < 3 {
		return UpdatePackRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 3 runes",
		}
	}

	if len(m.GetName()) > 256 {
		return UpdatePackRequestValidationError{
			field:  "Name",
			reason: "value length must be at most 256 bytes",
		}
	}

	return nil
}

// UpdatePackRequestValidationError is the validation error returned by
// UpdatePackRequest.Validate if the designated constraints aren't met.
type UpdatePackRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePackRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePackRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePackRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePackRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePackRequestValidationError) ErrorName() string {
	return "UpdatePackRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePackRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePackRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePackRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePackRequestValidationError{}

// Validate checks the field values on UpdatePackResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdatePackResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// UpdatePackResponseValidationError is the validation error returned by
// UpdatePackResponse.Validate if the designated constraints aren't met.
type UpdatePackResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePackResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePackResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePackResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePackResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePackResponseValidationError) ErrorName() string {
	return "UpdatePackResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePackResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePackResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePackResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePackResponseValidationError{}

// Validate checks the field values on ListPackV1Request with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListPackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetCursor() <= 0 {
		return ListPackV1RequestValidationError{
			field:  "Cursor",
			reason: "value must be greater than 0",
		}
	}

	if m.GetLimit() <= 0 {
		return ListPackV1RequestValidationError{
			field:  "Limit",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// ListPackV1RequestValidationError is the validation error returned by
// ListPackV1Request.Validate if the designated constraints aren't met.
type ListPackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackV1RequestValidationError) ErrorName() string {
	return "ListPackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackV1RequestValidationError{}

// Validate checks the field values on ListPackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPackV1ResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListPackV1ResponseValidationError is the validation error returned by
// ListPackV1Response.Validate if the designated constraints aren't met.
type ListPackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackV1ResponseValidationError) ErrorName() string {
	return "ListPackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackV1ResponseValidationError{}

// Validate checks the field values on RemovePackV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePackV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackId() <= 0 {
		return RemovePackV1RequestValidationError{
			field:  "PackId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RemovePackV1RequestValidationError is the validation error returned by
// RemovePackV1Request.Validate if the designated constraints aren't met.
type RemovePackV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePackV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePackV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePackV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePackV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePackV1RequestValidationError) ErrorName() string {
	return "RemovePackV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePackV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePackV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePackV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePackV1RequestValidationError{}

// Validate checks the field values on RemovePackV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemovePackV1Response) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Found

	return nil
}

// RemovePackV1ResponseValidationError is the validation error returned by
// RemovePackV1Response.Validate if the designated constraints aren't met.
type RemovePackV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemovePackV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemovePackV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemovePackV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemovePackV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemovePackV1ResponseValidationError) ErrorName() string {
	return "RemovePackV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemovePackV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemovePackV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemovePackV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemovePackV1ResponseValidationError{}
