global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - logistic-pack-api:9100
        - logistic-pack-retranslator:9101
        # - host.docker.internal:9100 # for local grpc-server
        # - host.docker.internal:9101 # for local retranslator
