syntax = "proto3";

package StormBeaver.logistic_pack_api.v1;

import "validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/StormBeaver/logistic-pack-api/pkg/logistic-pack-api;logistic_pack_api";

// LogisticPackApiService - Service for working with packs
service LogisticPackApiService {
  
  //CreatePackv1 - Create a new pack
  rpc AddPackV1(AddPackV1Request) returns (AddPackV1Response) {
       option (google.api.http) = {
      post: "/createPack"
      body: "*"
    };
  }

  // GetPackV1 - Describe a pack
  rpc GetPackV1(GetPackV1Request) returns (GetPackV1Response) {
    option (google.api.http) = {
      post: "/getPack"
      body: "*"
    };
  }

  //ListPackv1 - list all packs
  rpc ListPackV1(ListPackV1Request) returns (ListPackV1Response) {
       option (google.api.http) = {
      post: "/listPacks"
      body: "*"
    };
  }

  //UpdatePackV1 - update already existing pack
  rpc UpdatePackV1(UpdatePackV1Request) returns (UpdatePackV1Response) {
       option (google.api.http) = {
      post: "/updatePack"
      body: "*"
    };
  }

  //RemovePackV1 - remove a pack
  rpc RemovePackV1(RemovePackV1Request) returns (RemovePackV1Response) {
       option (google.api.http) = {
      post: "/removePack"
      body: "*"
    };
  }
}

message Pack {
  uint64 id  = 1;
  string name = 2;
  google.protobuf.Timestamp created = 3;
  string describe = 4;
}

message AddPackV1Request {
  string name = 1 [(validate.rules).string = {min_len: 3, max_bytes:256}];
  string describe = 2 [(validate.rules).string = {max_bytes:512}];
}

message AddPackV1Response {
  uint64 pack_id = 1;
  string describe = 2 [(validate.rules).string = {max_bytes:512}];
}

message GetPackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
}

message GetPackV1Response {
  Pack value = 1;
}

message UpdatePackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
  string name = 2 [(validate.rules).string = {min_len: 3, max_bytes:256}];
  string describe = 3 [(validate.rules).string = {max_bytes:512}];
}

message UpdatePackV1Response {
  bool found = 1;
}

message ListPackV1Request {
  uint64 cursor = 1 [(validate.rules).uint64.gt = 0];
  uint64 limit = 2 [(validate.rules).uint64.gt = 0];
}

message ListPackV1Response {
  repeated Pack items = 1;
}

message RemovePackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
}

message RemovePackV1Response {
  bool found = 1;
}