syntax = "proto3";

package ozonmp.logistic_pack_api.v1;

import "validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/ozonmp/logistic-pack-api/pkg/logistic-pack-api;logistic_pack_api";

// LogisticPackApiService - Service for working with packs
service LogisticPackApiService {
  // DescribePackV1 - Describe a pack
  rpc DescribePackV1(DescribePackV1Request) returns (DescribePackV1Response) {
    option (google.api.http) = {
      get: "/v1/packs/{pack_id}"
    };
  }
}

message Pack {
  uint64 id  = 1;
  uint64 foo = 2;
  google.protobuf.Timestamp created = 3;
}

message DescribePackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
}

message DescribePackV1Response {
  Pack value = 1;
}
