syntax = "proto3";

package stormbeaver.logistic_pack_api.v1;

import "validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/stormbeaver/logistic-pack-api/pkg/logistic-pack-api;logistic_pack_api";

// LogisticPackApiService - Service for working with packs
service LogisticPackApiService {
  //CreatePackv1 - Create a new pack
  rpc AddPackV1(AddPackV1Request) returns (AddPackV1Response) {
       option (google.api.http) = {
      post: "/v1/packs/create"
    };
  }

  // GetPackV1 - Describe a pack
  rpc GetPackV1(GetPackV1Request) returns (GetPackV1Response) {
    option (google.api.http) = {
      get: "/v1/packs/{pack_id}"
    };
  }

  //ListPackv1 - list all packs
  rpc ListPackV1(ListPackV1Request) returns (ListPackV1Response) {
       option (google.api.http) = {
      get: "/v1/packs/{cursor}/{limit}"
    };
  }

  //UpdatePackV1 - update already existing pack
  rpc UpdatePackV1(UpdatePackRequest) returns (UpdatePackResponse) {
       option (google.api.http) = {
      put: "/v1/packs/update/{pack_id}"
    };
  }

  //RemovePackV1 - remove a pack
  rpc RemovePackV1(RemovePackV1Request) returns (RemovePackV1Response) {
       option (google.api.http) = {
      delete: "/v1/packs/remove"
    };
  }
}

message Pack {
  uint64 id  = 1;
  string name = 2;
  google.protobuf.Timestamp created = 3;
}

message AddPackV1Request {
  string name = 1 [(validate.rules).string = {min_len: 3, max_bytes:256}];
}

message AddPackV1Response {
  uint64 pack_id = 1;
}

message GetPackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
}

message GetPackV1Response {
  Pack value = 1;
}

message UpdatePackRequest {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
  string name = 2 [(validate.rules).string = {min_len: 3, max_bytes:256}];
}

message UpdatePackResponse {
  bool found = 1;
}

message ListPackV1Request {
  uint64 cursor = 1 [(validate.rules).uint64.gt = 0];
  uint64 limit = 2 [(validate.rules).uint64.gt = 0];
}

message ListPackV1Response {
  repeated Pack items = 1;
}

message RemovePackV1Request {
  uint64 pack_id = 1 [(validate.rules).uint64.gt = 0];
}

message RemovePackV1Response {
  bool found = 1;
}
